### ISSUE TITLE
ERROR: Unsatisfiable requirements detected for package SDPT3

### ISSUE THREAD

**Issue by maihoanganh** [jump-dev/SDPT3.jl#9]
I get the following issue when I try to install SDPT3.jl:

(v1.3) pkg> add SDPT3
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package SDPT3 [e33b2407]:
 SDPT3 [e33b2407] log:
 ├─possible versions are: 0.0.1-0.0.2 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.0.2
 └─restricted by compatibility requirements with MATLAB [10e44e05] to versions: uninstalled — no versions left
   └─MATLAB [10e44e05] log:
     ├─possible versions are: [0.7.0-0.7.3, 0.8.0-0.8.2] or uninstalled
     └─restricted to versions 0.8.2 by an explicit requirement, leaving only versions 0.8.2

I am using Ubuntu 18.04.4 LTS. Could you kindly help me fix it?

**Comment by odow** [comment]
Try `] add MATLAB@0.7` then `] add SDPT3`. We need to update the compatibility of SDPT3.jl.

**Comment by odow** [comment]
Actually. Try 
```
] up
] add SDPT3#odow-patch-1`
] up
```

x-ref: https://github.com/jump-dev/SDPT3.jl/pull/10

**Comment by maihoanganh** [comment]
I tried ```] add MATLAB@0.7``` and ```] add SDPT3@0.0.1```. 
Then type ```] update MATLAB``` and ```] update SDPT3```. The package is therefore successfully installed.

However, running ```using SDPT3```, I got the previous issue [#7](https://github.com/jump-dev/SDPT3.jl/issues/7#issue-703550350).
I have fixed it by the following command lines in terminal before opening Julia:
```
export MATLAB_HOME="/usr/local/MATLAB/R2018a"
export PATH="${PATH}:${MATLAB_HOME}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${MATLAB_HOME}/glnxa64:/usr/local/MATLAB/R2018a/sys/os/glnxa64"
```
according to [#158](https://github.com/JuliaInterop/MATLAB.jl/issues/158#issue-417345488).

It works well now. Many thanks for your package.
